events {}

http 
{
    server
    {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        location /api/ 
        {
            proxy_pass http://backend:3000;
        }

        location / 
        {
            proxy_pass http://frontend:5173;
        }
    }
}